tidev/ti.map

ios/Classes/TiMapView.m
ios/documentation/changelog.md
ios/manifest

Details and test in Jira ticket [TIMOB-18510](https://jira.appcelerator.org/browse/TIMOB-18510)

[TiMOB-18510] iOS - Fixed map draggable map pins

---

apidoc/Map.yml

Opened as `<View>` but closed as `</Module>`
https://jira.appcelerator.org/browse/TIDOC-2202

[TIDOC-2202] Typo in Maps Example

---

apidoc/View.yml
ios/Classes/TiMapView.m
ios/manifest

**(In progress)**
JIRA: https://jira.appcelerator.org/browse/TIMOB-19215

[TIMOB-19215] Fix click events

---

apidoc/Map.yml
apidoc/StreetViewPanorama.yml

At the end of the Map.yml file, there are two example. The last example
doesn’t have an “examples” header which was causing the valid yaml to
treat the last example as a method (which passes the validation test)
but results in rendering no content. With the additional insertion of
examples:﻿ on line 363 of Map.yml, the content shows up again.

Fixed broken page (TIDOC-2450)

---

ios/Classes/TiMapView.m

Fix to returned property animated. Was always returning true.
The fix includes (and should be): If the User pans with their finger
the map, the animated property returns false, if you animate the map
programatically it returns true.

Bug Fix: regionchanged and regionwillchange returned animated was always true

---

android/documentation/changelog.md
android/manifest
android/src/ti/map/ViewProxy.java

- Fix `addPolyline()` to use `handleAddPolyline()`
- Bump version to `3.0.2`
```Javascript
var map = require('ti.map'),
mapview = map.createView({}),
polyline = map.createPolyline({
name: 'polyline_object',
strokeWidth: 3,
strokeColor: '#ffff00',
points: [
{latitude:53.677150, longitude:-7.728051},
{latitude:60.860020, longitude:8.667197},
{latitude:50.396644, longitude:9.769200},
{latitude:47.657334, longitude:-0.213136}
]
}),
polygon = map.createPolygon({
name: 'polygon_object',
strokeWidth: 3,
strokeColor: '#ffff00',
fillColor: '#ff00ff',
points: [
{latitude:53.677150, longitude:-7.728051},
{latitude:60.860020, longitude:8.667197},
{latitude:50.396644, longitude:9.769200},
{latitude:47.657334, longitude:-0.213136}
]
});
mapview.addPolygon(polygon);
mapview.addPolyline(polyline); …
```

[TIMOB-24039] Fix addPolyline() handler

---

android/documentation/changelog.md
android/manifest
android/src/ti/map/TiUIMapView.java

JIRA: https://jira.appcelerator.org/browse/MOD-2334
A MapView with userLocation:true in TSS will crash the app if you don't allow the Android M ACCESS_FINE_LOCATION.

[MOD-2334] Android: Fix userLocation crash when permissions are not set

---

android/documentation/changelog.md
android/manifest

- Bump to `3.3.1`
- [android-3.3.1](https://github.com/appcelerator-modules/ti.map/releases/tag/android-3.3.1) built using `6.2.0.GA`

[TIMOB-25288] Bump to 3.3.1

---

android/src/ti/map/MapModule.java
android/src/ti/map/TiUIMapView.java

**JIRA:** https://jira.appcelerator.org/browse/MOD-2401
**Description:**
Add a click event for deselecting annotations when clicking directly on another one.
**Note:** I am OK with implementing it this way for parity's sake, but I think such an event may be better suited not as a `click` one. For both platforms. IMO selecting/deselecting an annotation may be originating not only from a click, but for instance from `Modules.Map.View.selectAnnotation()`. So it makes sense to me to have a `click` event and a `select` event that get naturally combined when one is the cause of the other. We can consider that for a future major version of the module maybe?
CC: @hansemannn, @jquick-axway, @Topener  
**Test case:**
In the JIRA ticket.

[MOD-2401] Ti.Map: Inconsistency between iOS and Android click events on Annotations

---

android/src/ti/map/TiUIMapView.java

**JIRA:** https://jira.appcelerator.org/browse/MOD-2458
**Description:**
Fix removing of annotations when clustering is enabled.
Fix updating the map when annotations are added/removed with clustering enabled.
**Note:** I haven't updated the manifest, because I think we can put it together with this PR (https://github.com/appcelerator-modules/ti.map/pull/244) for 4.3.2
**Test case:**
There is a good test case in the JIRA tickets.

[MOD-2458] Android Ti.Maps removing annotation issues 4.3.0 with clusters

---

android/manifest
android/src/ti/map/MapModule.java
android/src/ti/map/TiUIMapView.java
apidoc/View.yml

**JIRA:** https://jira.appcelerator.org/browse/MOD-2457
**Description:**
Expose `setIndoorEnabled()` API for Ti.Map on Android.
**Note:** I'd prefer we clear v4.3.1 of the module from possible issues and add this feature in the following version. Possibly together with Titanium 7.5.0. 
**Test case:** 
app.js
```js
var Map = require('ti.map'),
win = Ti.UI.createWindow(),
mapView = Map.createView({ region: {
longitude:  -73.993389,
latitude: 40.750389,
latitudeDelta: 0.002,
longitudeDelta: 0.002 }
}),
button = Ti.UI.createButton({ bottom: 10,
title: 'Indoor map - enabled'
});
button.addEventListener('click', function () {
mapView.indoorEnabled = !mapView.indoorEnabled;
button.title = mapView.indoorEnabled ? 'Indoor map - enabled' : 'Indoor map - disabled';
}); …
```

[MOD-2457] Android: Expose setIndoorEnabled API for Ti.Map

---

android/manifest
android/src/ti/map/MapModule.java
android/src/ti/map/TiUIMapView.java
apidoc/View.yml
ios/Classes/TiMapView.h
ios/Classes/TiMapView.m
ios/manifest
package-lock.json
package.json

**JIRA**: https://jira.appcelerator.org/browse/MOD-2545
**Description**:
Since the click event will fire twice when you click a different annotation I've added a parameter to see if the source was deselected or not. Same for clicking on the map instead of a second annotation.
```
var Map = require('ti.map');
var win = Ti.UI.createWindow({
height: Ti.UI.FILL,
width: Ti.UI.FILL
});
var map_view = Map.createView();
var south_korea = Map.createAnnotation({
latitude: '36.792452',
longitude: '127.995333',
title: 'South Korea',
pincolor: Map.ANNOTATION_BLUE
});
var north_korea = Map.createAnnotation({
latitude: '39.763824',
longitude: '126.856541',
title: 'North Korea',
pincolor: Map.ANNOTATION_RED
});
map_view.addAnnotation(south_korea);
map_view.addAnnotation(north_korea);
map_view.region = { …
```

feat: add deselected parameter in click event

---

android/example/app.js
android/example/ui.js

This PR removes the suggestion mentioned in the `app.js` as it causes the maps on Devices and simulators to go black. A change to the app ui on Android was made so the app text can be visible when using the example app.
Jira ticket: https://jira.appcelerator.org/browse/MOD-2549
**Note:** Issue of multi maps crashing the app can be tracked here: https://jira.appcelerator.org/browse/MOD-2548

Android: Update Android Example app 

---

android/manifest
android/src/ti/map/AnnotationProxy.java
android/src/ti/map/TiClusterRenderer.java
android/src/ti/map/TiMarker.java
package-lock.json

Had this error message during running my app:
```
INFO]  Choreographer: Skipped 74 frames!  The application may be doing too much work on its main thread.
[ERROR] TiExceptionHandler: (main) [66,251578] Attempt to invoke virtual method 'java.lang.String ti.map.AnnotationProxy.getTitle()' on a null object reference
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     ti.map.TiMarker.getTitle(TiMarker.java:60)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:835)
[ERROR] TiExceptionHandler:     com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2100(DefaultClusterRenderer.java:805)
[ERROR] TiExceptionHandler: …
```

Android: Null check in TiMarker

---

android/manifest
android/src/ti/map/MapModule.java
android/src/ti/map/PolylineProxy.java
apidoc/Map.yml
apidoc/Polyline.yml
package-lock.json
package.json
test/unit/specs/polyline.spec.js

```JS
var Map = require('ti.map');
var win = Ti.UI.createWindow({
height: Ti.UI.FILL,
width: Ti.UI.FILL
});
var map_view = Map.createView();
map_view.region = {
latitude: '37.3895100',
longitude: '-122.0502150',
zoom: 10
};
win.add(map_view);
var btn = Ti.UI.createButton({
title: "add route",
bottom: 10
})
win.add(btn);
var t = [Map.POLYLINE_JOINT_DEFAULT, Map.POLYLINE_JOINT_ROUND, Map.POLYLINE_JOINT_BEVEL];
var ti = 0;
var pl = null;
btn.addEventListener("click", function() {
if (pl) map_view.removePolyline(pl);
pl = Map.createPolyline({
points: [
[-122.0201890, 37.3316920],
[-122.0741890, 37.2223450],
[-122.0602150, 37.3895100]
],
strokeColor: '#ff00aa',
strokeWidth: 15,
jointType: t[ti]
});
map_view.addPolyline(pl);
ti++;
if (ti > 2) {
ti = 0;
}
})
win.open();
```
Add the possibility …

Android: Add jointTypes

---

android/build.gradle
android/manifest
android/src/ti/map/TiClusterRenderer.java
android/src/ti/map/TiUIMapView.java
package-lock.json
package.json

* Will fix https://github.com/appcelerator-modules/ti.map/issues/342
* Update to the latest android-map-utils
* removed one warning in the same file and reordered the imports (Android Studio suggestion)
* add custom renderer to add a null check
According to  https://github.com/googlemaps/android-maps-utils#adding-a-custom-info-window the listeners have to be updated to be used with the newest android-map-utils
Example code in: https://jira.appcelerator.org/browse/AC-6626

fix(android): marker click

---

android/manifest
android/src/ti/map/TiUIMapView.java

Relates #495 
Marker click event for pin is not visible when using a normal marker (not a cluster):
```js
var win = Titanium.UI.createWindow({
layout: "vertical"
});
let mapView = require('ti.map').createView({
region: {
latitude: 52.23,
longitude: 13.401,
latitudeDelta: 0.1,
longitudeDelta: 0.1
}
});
win.add(mapView);
let an1 = require("ti.map").createAnnotation({
latitude: 52.23,
longitude: 13.401,
title: "Anno 1",
subtitle: "Subtitle 1",
pincolor: Map.ANNOTATION_RED
});
mapView.annotations = [an1];
mapView.addEventListener("click", function(e) {
console.log(e.clicksource);
})
win.open();
```
current workaround:
add `clusterIdentifier:"test"`
[ti.map-android-5.3.4.zip](https://github.com/appcelerator-modules/ti.map/files/7487718/ti.map-android-5.3.4.zip)

fix(android): Marker click event

---

android/build.gradle
android/manifest
android/src/ti/map/MapModule.java

* Use new Map Renderer (https://developers.google.com/maps/documentation/android-sdk/renderer)
* updated map-utils
> An upgraded map renderer is available as of version 18.0.0 of the Maps SDK for Android. This renderer brings many improvements, including support for Cloud-based maps styling. You can opt-in to try the new renderer before it becomes the default renderer for Android devices, through a progressive rollout starting in March 2022 at the earliest.
[ti.map-android-5.4.0.zip](https://github.com/appcelerator-modules/ti.map/files/8108987/ti.map-android-5.4.0.zip)
there are a lot of debug messages ` ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.`

feat(android): use new map api

---

android/build.gradle
android/manifest

just some house keeping:
* update maps to 18.1.0. No big changes but they have some new styling options for Shapes we could implement (https://developers.google.com/maps/documentation/android-sdk/shapes#polyline-customization). Sadly they still log so much stuff :disappointed: 
* match android fragment version with the version that is in the SDK
* update map utils to 2.4.0 (also no big changes, https://github.com/googlemaps/android-maps-utils/releases/tag/v2.4.0)
[ti.map-android-5.5.0.zip](https://github.com/tidev/ti.map/files/9616509/ti.map-android-5.5.0.zip)

feat(android): version update

---

android/manifest
android/src/ti/map/AnnotationProxy.java

Caused by missing memory (which can happen). The error is `Uncaught Error: Could not copy bitmap to parcel blob.`
Beta: [ti.map-android-5.5.1.zip](https://github.com/tidev/ti.map/files/10232111/ti.map-android-5.5.1.zip)
```
at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
at android.graphics.Bitmap.writeToParcel(Bitmap.java:2140)
at com.google.android.gms.internal.maps.zzc.zze(com.google.android.gms:play-services-maps@@18.1.0:3)
at com.google.android.gms.internal.maps.zzg.zzg(com.google.android.gms:play-services-maps@@18.1.0:2)
at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(com.google.android.gms:play-services-maps@@18.1.0:2)
at ti.map.AnnotationProxy.handleImage(AnnotationProxy.java:324)
at ti.map.AnnotationProxy.processOptions(AnnotationProxy.java:27 …
```

fix: guard invalid blob creation

---

android/manifest
android/src/ti/map/CircleProxy.java
android/src/ti/map/PolygonProxy.java
android/src/ti/map/PolylineProxy.java
android/src/ti/map/RouteProxy.java

use non deprecated "toColor(string, activity)" for https://github.com/tidev/titanium_mobile/pull/13273
[ti.map-android-5.5.2.zip](https://github.com/tidev/ti.map/files/11463940/ti.map-android-5.5.2.zip)

fix(android): use activity in toColor

---

android/build.gradle
android/manifest
android/src/ti/map/TiMarker.java

* update map-utils (https://github.com/googlemaps/android-maps-utils/releases)
* added `getZIndex` to make it build with the new version (was added in map-utils 3.2.0)
* match androidx.fragment:fragment version with SDK version
**Null check update**
My PR into the Google map-utils repo ("null check") was accepted and merged by google :+1:  ! 
That should reduce some random "null errors" in the internal `onAnimationUpdate` function.
----
**Side note:**
`getColor` can be overwritten in TiCluserRenderer now to set custom colors like
```java
@Override
public int getColor(int clusterSize) {
final float hueRange = 220;
final float sizeRange = 300;
final float size = Math.min(clusterSize, sizeRange);
final float hue = (sizeRange - size) * (sizeRange - size) / (sizeRange * sizeRange) * hueRange; …
```

feat(android): update libraries, add "zIndex" getter

---

apidoc/Map.yml
ios/Classes/TiMapModule.h
ios/Classes/TiMapModule.m
ios/Classes/TiMapModuleAssets.m
ios/Classes/TiMapUtils.h
ios/Classes/TiMapUtils.m
ios/Classes/TiMapViewProxy.h
ios/manifest
ios/map.xcodeproj/project.pbxproj

See the new api docs for details!
Full example:
```js
import Map from 'ti.map';
const window = Ti.UI.createWindow();
const mapView = Map.createView({
mapType: Map.NORMAL_TYPE
});
window.add(mapView);
Map.addEventListener('didUpdateResults', event => {
console.warn('Found place:');
console.warn(event)
});
setTimeout(function() {
Map.search('Colosseum', {
// Optional: Define search region
region: {
latitude: 41.890560,
longitude: 12.494270,
latitudeDelta: 1,
longitudeDelta: 1,
},
// Optional: Define result types (POIs and/or address)
resultTypes: [Map.SEARCH_RESULT_TYPE_POINT_OF_INTEREST, Map.SEARCH_RESULT_TYPE_ADDRESS]
});
}, 2000)
window.open();
```
Download: [ti.map-iphone-7.3.0.zip](https://github.com/tidev/ti.map/files/12706539/ti.map-iphone-7.3.0.zip)

feat(ios): add new search completion APIs

---

android/manifest

just a version bump as it looks like the Release ZIP is not the master branch. The `toColor()` fix is not included there
[ti.map-android-5.6.1.zip](https://github.com/tidev/ti.map/files/13962810/ti.map-android-5.6.1.zip)
I'll create a PR for the Ti SDK once it is merged

chore(android): version bump
