tidev/ti.map

apidoc/Map.yml
=> [TIDOC-2023] Remove unneeded manifest tag

ios/Classes/TiMapView.m, ios/documentation/changelog.md, ios/manifest
JIRA here: https://jira.appcelerator.org/browse/TIMOB-17953
=> [TIMOB-17953] iOS: Fix undeclared annotation buttons appearing on iOS7

apidoc/Map.yml
https://jira.appcelerator.org/browse/TIDOC-2204
=> [TIDOC-2204] iOS Map Guides/APIDoc missing NSLocation* instructions for userLocation

ios/Classes/TiMapView.m, ios/documentation/changelog.md, ios/manifest
JIRA: https://jira.appcelerator.org/browse/TIMOB-19102
Resolved by making sure to use the main thread when adding and removing vectors (circle, polygone, polyline) to a map.
=> [TIMOB-19102] Resolve map crashes with vectors

apidoc/View.yml, ios/Classes/TiMapView.m, ios/documentation/changelog.md, ios/manifest
JIRA: https://jira.appcelerator.org/browse/MOD-2131
=> [MOD-2131] Fix dragging issues

ios/Classes/TiMapAnnotationProxy.h, ios/Classes/TiMapAnnotationProxy.m, ios/Classes/TiMapModule.h, ios/Classes/TiMapModule.m, ios/Classes/TiMapRouteProxy.m, ios/Classes/TiMapView.m, ios/Classes/TiMapViewProxy.m, ios/manifest
JIRA: https://jira.appcelerator.org/browse/MOD-2142
=> [MOD-2142] Resolve iOS9 deprecation- and conversation warnings

ios/Classes/TiMapView.h, ios/Classes/TiMapView.m, ios/manifest
JIRA: https://jira.appcelerator.org/browse/MOD-2178
=> [MOD-2178] Fix annotations crash

apidoc/View.yml, ios/Classes/TiMapIOS7View.m, ios/Classes/TiMapView.m, ios/manifest
[JIRA Ticket](https://jira.appcelerator.org/browse/MOD-2172)
=> [MOD-2172] Support new MKMapView properties

android/documentation/changelog.md, android/manifest, android/src/ti/map/AnnotationProxy.java, apidoc/Annotation.yml
JIRA: https://jira.appcelerator.org/browse/MOD-2205
=> [MOD-2205] Android: Support Blob image, bump to 2.3.8

android/documentation/changelog.md, android/manifest, android/src/ti/map/AnnotationProxy.java, android/src/ti/map/ViewProxy.java
JIRA https://jira.appcelerator.org/browse/TIMOB-20620
=> [TIMOB-20620] Android: Annotation.pincolor can't be changed if annotation added to mapView.

ios/Classes/TiMapView.m, ios/manifest
JIRA: https://jira.appcelerator.org/browse/TIMOB-20606
=> [TIMOB-20606] iOS: Fix "pinchangedragstate" event

apidoc/View.yml
[JIRA](https://jira.appcelerator.org/browse/MOD-2274?filter=-1)
=> [MOD-2274] iOS/Android: Update Docs

apidoc/Map.yml
https://jira.appcelerator.org/browse/TIDOC-2451
=> Updated Map.yml as requested in TIDOC-2451

android/documentation/changelog.md, android/manifest, android/src/ti/map/TiUIMapView.java, android/src/ti/map/ViewProxy.java, apidoc/View.yml
Jira: https://jira.appcelerator.org/browse/MOD-2311
Add setMapStyle to style the map via json from https://mapstyle.withgoogle.com/
```css
"#mapview": {
style:'[{"elementType":"geometry","stylers":[{"color":"#242f3e"}]},{"elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"elementType":"labels.text.fill","stylers":[{"color":"#746855"}]},{"elementType":"labels.text.stroke","stylers":[{"color":"#242f3e"}]},{"featureType":"administrative","elementType":"geometry","stylers":[{"color":"#757575"}]},{"featureType":"administrative.country","elementType":"labels.text.fill","stylers":[{"color":"#9e9e9e"}]},{"featureType":"administrative.land_parcel","stylers":[{"visibility":"off"}]},{"featureType":"administrative.locality","elementType":"labels.text.fill","stylers":[{"color":"#d59563"}]}, …
```
=> [MOD-2311] Android: add Map styling via json

ios/Classes/TiMapCustomAnnotationView.m
JIRA: https://jira.appcelerator.org/browse/MOD-2201
=> [MOD-2201] iOS: annotations with customView Disappears

android/documentation/changelog.md, android/manifest, android/src/ti/map/AnnotationProxy.java, android/src/ti/map/TiMarker.java, android/src/ti/map/TiUIMapView.java
- Release annotation objects when removing annotations
- Project in JIRA Ticket
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23269)
=> [TIMOB-23269] Android: Fix Annotation memory leak

android/documentation/changelog.md, android/manifest, android/src/ti/map/TiMarker.java, android/src/ti/map/TiUIMapView.java
- Fix `removeAnnotation` and `removeAllAnnotations`
- Do not destroy marker when removing
[JIRA Ticket](https://jira.appcelerator.org/browse/MOD-2337)
=> [MOD-2337] Android: Fix removeAnnotation

apidoc/Annotation.yml, ios/Classes/TiMapAnnotationProxy.h, ios/Classes/TiMapAnnotationProxy.m, ios/Classes/TiMapView.m
https://jira.appcelerator.org/browse/TIMOB-24375
=> [TIMOB-24375]: iOS Implement "Peek & Pop" for Map view Annotation

apidoc/Map.yml
Fixed broken link as mentioned in https://jira.appcelerator.org/browse/TIDOC-3170.
=> Fixed broken link in Map.yml

apidoc/ImageOverlay.yml, apidoc/View.yml, ios/Classes/TiMapImageOverlayProxy.h, ios/Classes/TiMapImageOverlayProxy.m, ios/Classes/TiMapImageOverlayRenderer.h, ios/Classes/TiMapImageOverlayRenderer.m, ios/Classes/TiMapView.h, ios/Classes/TiMapView.m, ios/Classes/TiMapViewProxy.h, ios/Classes/TiMapViewProxy.m, ios/manifest, ios/map.xcodeproj/project.pbxproj
https://jira.appcelerator.org/browse/MOD-2145
=> [Mod-2145] : (iOS)Ti.Map: Support Image Overlays

android/src/ti/map/TiUIMapView.java
- Improve `map` validation
- Project on JIRA: https://jira.appcelerator.org/secure/attachment/64875/TiLabelbug.zip
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25811)
=> [TIMOB-25811] Android: Improve validation

android/src/ti/map/ViewProxy.java, apidoc/View.yml, ios/Classes/TiMapView.m
**JIRA**: https://jira.appcelerator.org/browse/MOD-2345
=> [MOD-2345] iOS: Add parity for "padding" on MapView, use dictionary on Android

Jenkinsfile, android/manifest
appcelerator/titanium_mobile#9926
=> Try to build against latest v8/sdk build

android/manifest, android/timodule.xml
**JIRA**: https://jira.appcelerator.org/browse/MOD-2467
---
Also cleaned up the formatting of the `timodule.xml` to use consistent indentation.
=> fix(android): add „org.apache.http.legacy“ key for Android P bug

Jenkinsfile, ios/Classes/TiMapImageOverlayRenderer.m, ios/Classes/TiMapSnapshotterProxy.m, ios/map.xcodeproj/project.pbxproj, package-lock.json, package.json, test/unit/karma.unit.config.js
WIP to try and get the module building on Jenkins again
=> build: use sdk 8.1.1GA

ios/manifest
https://jira.appcelerator.org/browse/MOD-1630
=> MOD-1630: iOS: Update "ti.map" iOS manifest file's guid to match Android's

test/unit/specs/annotation.spec.js, test/unit/specs/camera.spec.js, test/unit/specs/route.spec.js
https://jira.appcelerator.org/browse/MOD-2618
=> MOD-2618 : Improve remaining classes Unit Test coverage

android/example/app.js, android/example/tests/lite.js, android/manifest, android/src/ti/map/MapModule.java, android/src/ti/map/TiUIMapView.java, apidoc/View.yml, package-lock.json, package.json
https://jira.appcelerator.org/browse/MOD-2609
=> Mod 2609(fix): Merging example for lite mode

android/manifest, android/src/ti/map/MapModule.java, android/src/ti/map/TiUIMapView.java, android/src/ti/map/ViewProxy.java, apidoc/View.yml, package-lock.json, package.json, test/unit/specs/view.spec.js
**JIRA:**
https://jira.appcelerator.org/browse/MOD-2631
**Description:**
add parameter `minClusterSize` to set the minimum cluster size (https://github.com/appcelerator-modules/ti.map/issues/267)
```
var Map = require('ti.map');
var win = Titanium.UI.createWindow();
var ann = [];
for (var i = 0; i < 30; i++) {
ann.push(Map.createAnnotation({
clusterIdentifier: 'abc',
collisionMode: Map.ANNOTATION_VIEW_COLLISION_MODE_RECTANGLE,
showAsMarker:true,
markerGlyphText:i.toString(),
markerColor:'blue',
markerGlyphColor:'green',
title:'Title',
subtitle: 'subtitle',
markerTitleVisibility: Map.FEATURE_VISIBILITY_VISIBLE,
markerSubtitleVisibility: Map.FEATURE_VISIBILITY_HIDDEN,
markerGlyphImage:'Flag.png',
markerSelectedGlyphImage:'social-facebook-icon.png', …
```
=> Android: minClusterSize

android/manifest, android/src/ti/map/PolygonProxy.java, android/src/ti/map/PolylineProxy.java, android/src/ti/map/RouteProxy.java, apidoc/Polyline.yml, apidoc/Route.yml, package-lock.json, package.json
In polygonproxy, polylineproxy and routesproxy with this new version we can use encoded coords. This accelerates
=> Android encoded polylines

ios/Classes/TiMapCircleProxy.m, ios/manifest, package-lock.json, package.json, test/unit/specs/circle.spec.js
https://jira.appcelerator.org/browse/MOD-2816
=> fix(ios): implement getter for property center

ios/Classes/TiMapAnnotationProxy.h, ios/Classes/TiMapAnnotationProxy.m, ios/Classes/TiMapPinAnnotationView.h, ios/Classes/TiMapView.m, ios/manifest, package-lock.json, package.json
JIRA: https://jira.appcelerator.org/browse/TIMOB-28465
=> chore: migrate from MKPinAnnotationView to MKMarkerAnnotationView

android/build.gradle, android/manifest, ios/manifest, package-lock.json, package.json
**Summary:**
- Updated iOS module version to 6.0.1.
- Updated Android module version to 5.3.3.
- Updated Android dependencies.
=> chore: update module versions
